### ISSUE TITLE
Any plan to cut a v0.1.0 release?

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#222]
This will unblock https://github.com/kubernetes-sigs/cluster-api/pull/8811, so we can get this provider accessible via clusterctl

**Comment by mcbenjemaa** [comment]
I'm looking to become a maintainer for this ipam provider.

**Comment by schrej** [comment]
We are planning to, yes. I was mainly waiting for #203 which we finally merged a few days ago. There is a [few things left](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/milestone/1), but then we'll at least cut a release candidate.
I'm considering to jump to 1.0.0 directly, as we're probably pretty feature complete. The only concern would be stability. I'd rely on some feedback from VMware to decide on that, since they've been using it a lot more (= at all) than we have.

**Comment by stmcginnis** [comment]
I'm guessing this is a sign of some progress here? :)

```
Error: failed to get provider components for the "in-cluster" provider: failed to get repository client for the IPAMProvider with name in-cluster: error creating the GitHub repository client: failed to get latest release: release not found for version v0.1.0-rc.0, please retry later or set "GOPROXY=off" to get the current stable release: 404 Not Found
```

**Comment by schrej** [comment]
Yep! Just waiting for the image: https://github.com/kubernetes/k8s.io/pull/6393 (and I also need to fix the manifests)
