### ISSUE TITLE
Discussion: Should Pools be validated for overlapping ranges?

### ISSUE THREAD

**Issue by tylerschultz** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#64]
As of writing this issue, the provider has no validation for pools that overlap. This may cause the provider to give out duplicate IPs, which could result in serious issues. We'd like to start a discussion about why or why not validation would be something desired.

We're interested in cases where rejecting a pool that overlaps another pool would be incorrect behavior.

**Comment by schrej** [comment]
I could see this as an optional feature that can be toggled as a command line flag.

Not sure if there are practical cases, but with NAT it's easily possible to have two clusters use the same subnet.
We could argue that they should be in different namespaces when this is the case, but don't like creating a restriction like that, which is why I would want it to be optional.
